travis: avoid erroring out on release branch.
* travis.yml.in (env): Remove ROCKSPEC setting.
(before_install): Clean up LuaJIT-2.0.3 directory droppings.
(install): If there is a release rockspec use it, falling back
to git rockspec otherwise.
(script): Autofool timestamps when we can avoid bootstrapping
on ready-to-configure release branches.
* build-aux/bootstrap.slingshot (slingshot_update_travis_yml):
Substitute for @VERSION@ when generating .travis.yml.

Signed-off-by: Gary V. Vaughan <gary@gnu.org>

diff --git a/travis.yml.in b/travis.yml.in
--- a/travis.yml.in
+++ b/travis.yml.in
@@ -8,8 +8,6 @@ env:
     - _LINK="libtool --mode=link --tag=CC gcc"
     - _LIBS="-lm -Wl,-E -ldl -lreadline"
 
-    - ROCKSPEC=@PACKAGE@-git-1.rockspec
-
     - prefix=/usr/local
     - bindir=$prefix/bin
     - incdir=$prefix/include
@@ -89,7 +87,7 @@ before_install:
 
   # Tidy up file droppings.
   - cd $TRAVIS_BUILD_DIR
-  - rm -rf lua-5.3.0 lua-5.2.3 lua-5.1.5 luarocks-2.2.0
+  - rm -rf lua-5.3.0 lua-5.2.3 lua-5.1.5 LuaJIT-2.0.3 luarocks-2.2.0
 
 
 install:
@@ -100,19 +98,28 @@ install:
        sudo luarocks install --server=http://rocks.moonscript.org/manifests/gvvaughan $rock;
     done'
 
-  # Initial bootstrap to generate Makefile for rockspecs.
-  - ./bootstrap
-  - ./configure LUA="$LUA"
-  - make rockspecs V=1
-    || cat $ROCKSPEC
-
-  # Rerun bootstrap automatically from git rockspec.
+  # Build from rockspec.
+  - export ROCKSPEC=@PACKAGE@-@VERSION@-1.rockspec
+  - 'test -f "$ROCKSPEC" || ROCKSPEC=@PACKAGE@-git-1.rockspec'
   - sudo luarocks make $ROCKSPEC LUA="$LUA"
-  - sudo make clean
+
+  # Clean up files created by root
+  - sudo git clean -dfx
+  - sudo rm -rf slingshot
 
 
 script:
-  - make all check V=1
+  - 'if test -f configure; then
+      touch aclocal.m4;
+      sleep 1; touch Makefile.in;
+      sleep 1; touch config.h.in;
+      sleep 1; touch configure;
+    else
+      ./bootstrap --verbose;
+    fi'
+  - test -f Makefile || ./configure --disable-silent-rules LUA="$LUA"
+  - make
+  - make check V=1
 
 
 # Run sanity checks on CI server, ignoring buggy automakes.
@@ -123,4 +130,4 @@ after_success:
        fi;
        printf "local-checks-to-skip %s sc_vulnerable_makefile_CVE-2012-3386\n" "$_assign";
      } >> build-aux/sanity-cfg.mk'
-  - 'make syntax-check || :'
+  - 'make syntax-check || : this will usually fail on the release branch'
